
family = "noto-glyf_colr_1"
output_file = "noto-glyf_colr_1.ttf"
color_format = "glyf_colr_1"

[axis.wght]
name = "Weight"
default = 400

[master.regular]
style_name = "Regular"
srcs = ["../font-srcs/noto-emoji/svg/emoji_u0023.svg", "../font-srcs/noto-emoji/svg/emoji_u0023_20e3.svg"]

[master.regular.position]
wght = 400
